trigger:
- master  # Or your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository'
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/clementmaxwell/PayNetMiniProject/_git/API'
    sourceGitRepositoryPersonalAccessToken: '$(sourcePAT)'
    destinationGitRepositoryUri: 'https://github.com/nalhassanal/APIDest.git'
    destinationGitRepositoryPersonalAccessToken: '$(destPAT)'
    # Optional:
    # sourceGitRepositoryCloneDirectoryName: ''
    # sourceVerifySSLCertificate: true
    # destinationVerifySSLCertificate: true
