variables:
- group: mirror

trigger:
- master

pool:
  name: 'default'  # or 'ubuntu-latest' for Microsoft-hosted

steps:
- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository'
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/clementmaxwell/PayNetMiniProject/_git/API'
    sourceGitRepositoryPersonalAccessToken: '$(sourcePAT)'
    destinationGitRepositoryUri: 'https://github.com/nalhassanal/APIDest.git'
    destinationGitRepositoryPersonalAccessToken: '$(destPAT)'
    sourceVerifySSLCertificate: true
    destinationVerifySSLCertificate: true
